### ISSUE TITLE
Exclude from the graph view

### ISSUE THREAD

**Issue by gmmazza** [badrbouslikhin/obsidian-vault-changelog#12]
Could be possible to hide the changelog.md file from the graph view?
Thank you

**Comment by badrbouslikhin** [comment]
I apologize for the delay in responding to this issue. Thank you for reaching out and submitting your feature request. I have reviewed the plugin API, but unfortunately, I couldn't find a way to achieve this feature.

One possible workaround would be to add your changelog file to the excluded files list. However, please note that this would hide the file from search results, unlinked mentions, and make it less noticeable in the quick switcher and link suggestions.

<img width="1014" alt="Screenshot 2023-06-20 at 00 25 01" src="https://github.com/badrbouslikhin/obsidian-vault-changelog/assets/7818591/56484deb-b0fa-415a-b0dc-ce40e4bb81f9">
