### ISSUE TITLE
Mistake?

### ISSUE THREAD

**Issue by 7Codez** [badrbouslikhin/obsidian-vault-changelog#20]
you said in readme. :
notes/misc/changelog.md
<vault>/.obsidian/plugins
.
├── notes
│   └── misc
│   └── changelog.md
├── pictures
├── some-note.md
└── some-other-note.md

solv:
.
├── notes
│   └── misc
│      └── changelog.md
├── pictures
├── some-note.md
└── some-other-note.md

**Comment by badrbouslikhin** [comment]
Hi there,
I apologize for the delay in responding to this issue. Thank you for reaching out and bringing this up, 59eda0e62d968354c2e0610c505ec57f259d6ff0 fixes the issue.
